### ISSUE TITLE
iOS App not available in Dutch App Store

### ISSUE THREAD

**Issue by second2falcon** [Aayush9029/RifiApp#4]
As the title says, the RiFi App is not available in the Dutch App Store. 
I would like to know if this is intentional or not as the app seems very handy.

**Comment by Aayush9029** [comment]
Hi! Thanks for the interest.

RiFi was replaced by it's successor  https://apps.apple.com/ca/app/khula/id1598837354

**Comment by second2falcon** [comment]
Sad, but okay. 
In my eyes, Rifi looked a lot cooler as it was more Apple-like as compared to Khula.

**Comment by Aayush9029** [comment]
@second2falcon i absolutely agree! Infact im working on updating Khula’s UI and UX to be very apple like.

Granted the target os will be iOS 17 and macOS Ventura or later.

If you’re interested I’ll send you the TestFlight link when it’s ready!

**Comment by second2falcon** [comment]
> @second2falcon i absolutely agree! Infact im working on updating Khula’s UI and UX to be very apple like.
> 
> Granted the target os will be iOS 17 and macOS Ventura or later.
> 
> If you’re interested I’ll send you the TestFlight link when it’s ready!

@Aayush9029 I'd be down to do that for sure. I am running the iOS 17 dev beta anyways.
